name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 8 */4 * *'
  workflow_dispatch:

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Realizar petición REST a Supabase
        run: |
          URL="https://gprpyxeamjmvmqtkjvtn.supabase.co"
          KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwcnB5eGVhbWptdm1xdGtqdnRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTE1NjE3MzQsImV4cCI6MjEwNzEzNzczNH0.GeGAmqywLM7HsfUIGj9i6f50vhf_ijh9CWc-Y-DdANA"
          
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X GET "$URL/rest/v1/" \
            -H "apikey: $KEY" \
            -H "Authorization: Bearer $KEY")
          
          echo "Respuesta HTTP: $STATUS"
          if [ "$STATUS" -eq 200 ]; then
            echo "Supabase está activo y responde correctamente."
          else
            echo "Error o estado inesperado: $STATUS"
            exit 1
          fi